version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=pokedex
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - '3366:3306'

  react-app:
    image: pokedex-frontend-image
    ports:
      - "3000:3000"

